### ISSUE TITLE
Feature request - false by default

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt-contrib-triggered#17]
I think that once Triggered is enabled in your course that the default should be false so it is not active on EVERY component from the start?

That way you can turn it on for only the ones you want. I can see users wanting to have this on a few components maybe, but not more than half, so having it off for each component by default would be better?

Do you agree?

**Comment by moloko** [comment]
+1

**Comment by oliverfoster** [comment]
+1

**Comment by hrajotia** [comment]
@hmaffin The triggered object is always suppose to placed in a component, currently it do not have any course level configuration. I've updated the [example.json](https://github.com/adaptlearning/adapt-contrib-triggered/blob/master/example.json), please have a look.

You can change the `_isEnabled` attribute for individual component to make them visible by triggered extension.

If you want then I can add a config at course level (i.e in `course.json`) -
```javascript
"_triggered": {
    "_isEnabled": false
}
```
This will override `_isEnabled` attribute for all existing triggered enabled components!

So is it that you're looking for?

**Comment by moloko** [comment]
@hrajotia I think what @hmaffin is referring to is that the `_isEnabled` property is set to default to `true` in [properties.schema](adapt-contrib-triggered/blob/master/properties.schema#L37)

**Comment by hrajotia** [comment]
@moloko I think it have default as `true` see https://github.com/adaptlearning/adapt-contrib-triggered/blob/master/properties.schema#L37

**Comment by moloko** [comment]
@hrajotia yes that's what I mean, changing this to `false` should solve @hmaffin's issue

**Comment by hrajotia** [comment]
Alright... fair enough.. :+1:

**Comment by moloko** [comment]
we had the same problem with our [adapt-hint extension](/cgkineo/adapt-hint); if you set the `default` for `_isEnabled` to `true` in properties.schema then it will automatically get added to and switched on for every single component in the course

**Comment by hrajotia** [comment]
Hmm.. should be also add a course level config for trigger to disable it throughout the course?

**Comment by moloko** [comment]
yes I think that could also be useful

**Comment by hrajotia** [comment]
nice... thanks.. :+1:

**Comment by hmaffin** [comment]
Sorry I didn't jump in I was training all day but yes that's what I meant. Thanks for translating moloko :)
