### ISSUE TITLE
Last thing!

### ISSUE THREAD

**Issue by hmaffin** [adaptlearning/adapt-contrib-triggered#19]
OK works brilliantly being disabled by default and the hide me button is now visible correctly, but is not aligned with the component that is now showing, thus...

![image](https://cloud.githubusercontent.com/assets/11558341/14737382/b471f454-0873-11e6-9733-c2913cf0ada9.png)

Would it look smarter to have it align with the edges of the component, or to be able to type in the top and right of the hide button as you can with the show button?

Great work!

**Comment by hrajotia** [comment]
So to achieve this I'd like to propose below structure -
```json
"_triggered": {
    "_isEnabled": true,
    "showButton": {
        "_top": 30,
        "_left": 30,
        "buttonText": "Click me to show"
    },
    "hideButton": {
        "_top": -10,
        "_left": 60,
        "buttonText": "Click me to hide"
    }
}
```
*Note: measurements are in percentages*

Is anyone have better approach on this?
