### ISSUE TITLE
Doesn't work if you apply to both of 2 components next to each other

### ISSUE THREAD

**Issue by hbaileylxd** [adaptlearning/adapt-contrib-triggered#21]
The two triggered settings interfere with the other. In the diagram below I have two half width graphics both with triggered applied. It starts with just one Show button visible (the left), and when i click on that it shows the other component instead then gets itself in a mess!:

![image](https://cloud.githubusercontent.com/assets/11558341/17439494/483a78c4-5b20-11e6-8712-6f7ee44d833b.png)

**Comment by OscarArango** [comment]
Also does anyone know if theres an easy way to rotate the process for this?  show on load then hide on button click.  The javascript seems a bit over kill for such a simple plugin.
