### ISSUE TITLE
Reversing the process

### ISSUE THREAD

**Issue by OscarArango** [adaptlearning/adapt-contrib-triggered#22]
Does anyone know if theres an easy way to rotate the process for this? show on load then hide on button click. The javascript seems a bit over kill for such a simple plugin.

**Comment by oliverfoster** [comment]
swap these behaviours around:

https://github.com/adaptlearning/adapt-contrib-triggered/blob/master/js/adapt-contrib-triggered.js#L77 and https://github.com/adaptlearning/adapt-contrib-triggered/blob/master/js/adapt-contrib-triggered.js#L50-L54

if you can make the plugin more concise, please submit a PR, it'd make everyone's lives easier.
