### ISSUE TITLE
Inconsistent results with adapt-contrib-trickle on mobile devices

### ISSUE THREAD

**Issue by chrisgillison** [adaptlearning/adapt-contrib-triggered#24]
This is a great extension but on mobile devices, if you're using trickle, the trickle button sometimes doesn't appear when you've clicked the triggered-show button. Samsung Galaxy TabA 10.1 vertical it works, same device horizontal it doesn't, iPad pro it works in both orientations, iPhone 6s it doesn't work in either orientation.

**Comment by oliverfoster** [comment]
this is probably a trickle bug
